markdown: kramdown
permalink: /:year/:month/:day/:title/
url: https://zhulb.github.io
app: /webfrogs.github.com
author: nswebfrog
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 15


# Gems
gems: [jekyll-paginate]

theme: jekyll-theme-merlot
